import Head from "next/head";
import { Inter } from "next/font/google";

import Link from "next/link"
import About from "@/components/About/About";
import Contacts from "@/components/Contacts/Contacts";
import Proyects from "@/components/Proyects/Proyects";
import Skills from "@/components/Skills/Skills";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className="relative mx-auto  lg:p-10">
        <nav className="  m-auto  pr-2  animate-bounce hover:animate-none fixed right-0 left-0 z-50 container max-w-xl w-xl mt-10 lg:mt-0 h-10  rounded-full content-center  border  border-cyan-300 hover:opacity-100 bg-white/30 backdrop-blur">
          <div className="flex flex-row justify-center ">
            <div className="flex  order-none space-x-4 gap-3  text-black font-mono text-md font-bold ">
              <Link href={"#about"} className="duration-700 inline-block hover:scale-125  hover:text-cyan-300">Informacion</Link>
              <Link href={"#proyects"} className="m-0 duration-700 inline-block hover:scale-125  hover:text-cyan-300">Proyectos</Link>
              <Link href={"#skills"} className="duration-700 inline-block hover:scale-125  hover:text-cyan-300">Habilidades</Link>
              <Link href={"#contacts"} className="duration-700 inline-block hover:scale-125  hover:text-cyan-300">Contactos</Link>
            </div>
          </div>
        </nav>

        <section className="flex flex-col  backdrop-blur w-full   content-center  p-10 m-auto">
          
          <div id="about">
            <About></About>
          </div>
          
          <div id="proyects" className="flex  p-5 justify-center w-full  top-0">
            <div className="w-4/2">
            <h1 className="p-3 text-3xl text-white font-bold sticky top-0 w-full text-center">⚒️ Proyectos ⚒️</h1>
            <hr className='border-solid border-grey w-full'/>
            <Proyects></Proyects>
            </div>
          </div>
          
          <div id="skills" className="flex flex-col p-5 gap-4  justify-center w-full  top-0">
            <h1 className="text-4xl text-center text-white font-bold">🧰 Habilidades 🧰</h1>
            <Skills></Skills>
          </div>
          
          <div id="contacts" className="flex  gap-4 flex-col justify-center  top-0">
            <h1 className="text-4xl text-center p-5 text-white font-bold">🪪 Contactos 🪪</h1>
            <Contacts></Contacts>
          </div>
        </section>
      </main>
    </>
  );
}
